name: Tests

on:
  pull_request

jobs:
  runTests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry
        cd gen3release-sdk
        poetry install
    - name: Test with pytest
      run: |
        cd gen3release-sdk/tests
        poetry run pytest -vv
